spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ''
        url: JDBC:mysql://localhost:3306/greeting?createDatabaseIfNotExist=true
        username: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop

